
name: workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - testing

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version '3.22.2'

      - name: Install Dependencies
        run: flutter pub get

      - name: Build flutter application
        run: flutter build web










