
name: workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - testing

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build Frontend
        run: | 
          flutter run





